In [1]:
import numpy as np
from pyutils.polyutils import *
from scipy.spatial import ConvexHull as ch
from scipy.spatial import Delaunay

import coxeter
from coxeter.families import (
    ArchimedeanFamily as archfam,
)
from coxeter.families import (
    JohnsonFamily as johnfam,
)
from coxeter.families import (
    PlatonicFamily as platfam,
)
from coxeter.shapes import ConvexPolyhedron, Polyhedron


In [2]:
cube = platfam.get_shape("Cube")
# tetr = platfam.get_shape("Tetrahedron")
mbri = johnfam.get_shape("Metabidiminished Rhombicosidodecahedron")
# icosi = archfam.get_shape("Icosidodecahedron")
# poly = cube

In [9]:
archs = get_shortcodes()
# archs

In [5]:
cube.equations

array([[-0. , -0. , -1. , -0.5],
       [ 0. , -1. ,  0. , -0.5],
       [ 1. , -0. , -0. , -0.5],
       [-1. , -0. , -0. , -0.5],
       [ 0. ,  1. , -0. , -0.5],
       [-0. , -0. ,  1. , -0.5]])

In [4]:
simplex_normals = self._simplex_equations[:, :3]
# Generate boolean array checking which simplices share a normal (within tolerance)
is_coplanar = np.all(np.abs(simplex_normals[:, None] - simplex_normals) < tol, axis=2)
# Convert boolean array into ragged list of coplanar simplices
coplanar_simplices = list({tuple(np.where(coplanar)[0]) for coplanar in is_coplanar})
faces = []
ordered_simplices = []
simplex_equation_indices = []
for face_simplex_indices in coplanar_simplices:
    # Get unique vertex indices from faces and convert to numpy array
    faces.append(
        np.fromiter(set(self.simplices[[face_simplex_indices]].flat), np.int32)
    )
    # Add simplex indices back into list that matches face ordering
    ordered_simplices.extend(face_simplex_indices)
    simplex_equation_indices.append(face_simplex_indices[0])

# Assign faces and associated data to variables
self._faces = faces
self._coplanar_simplices = coplanar_simplices
self._equations = self._simplex_equations[simplex_equation_indices]

# Reorder list of simplices (and related properties) to match the list of faces
self._simplices = self._simplices[ordered_simplices]
self._simplex_equations = self._simplex_equations[ordered_simplices]
self._simplex_neighbors = self._simplex_neighbors[ordered_simplices]

NameError: name 'self' is not defined

In [5]:
poly = mbri
# for poly, name in [findpoly(a) for a in archs]:
# poly = mbri
tol = 1e-14
simplex_normals = poly._simplex_equations
# Generate boolean array checking which simplices share a normal (within tolerance)
is_coplanar = np.all(np.abs(simplex_normals[:, None] - simplex_normals) < tol, axis=2)
# Convert boolean array into ragged list of coplanar simplices
coplanar_simplices = list({tuple(np.where(coplanar)[0]) for coplanar in is_coplanar})
faces = []
ordered_simplices = []
simplex_equation_indices = []
for face_simplex_indices in coplanar_simplices:
    # Get unique vertex indices from faces and convert to numpy array
    faces.append(
        np.fromiter(set(poly.simplices[[face_simplex_indices]].flat), np.int32)
    )
    # Add simplex indices back into list that matches face ordering
    ordered_simplices.extend(face_simplex_indices)
    simplex_equation_indices.append(face_simplex_indices[0])
assert {tuple(sorted(i)) for i in faces} == {tuple(sorted(i)) for i in poly.faces}
print(ordered_simplices)

[81, 82, 2, 5, 35, 36, 8, 12, 13, 21, 22, 27, 28, 29, 40, 41, 61, 62, 63, 17, 18, 70, 71, 72, 73, 74, 75, 76, 77, 49, 50, 51, 68, 69, 78, 79, 80, 54, 55, 64, 65, 83, 84, 85, 86, 87, 88, 89, 90, 4, 1, 7, 59, 60, 56, 57, 58, 23, 24, 10, 11, 19, 20, 14, 15, 16, 47, 48, 0, 42, 43, 32, 33, 34, 37, 38, 39, 3, 9, 44, 45, 46, 6, 52, 53, 91, 92, 93, 94, 95, 66, 67, 30, 31, 25, 26]


In [6]:
np.argwhere(is_coplanar)
# now, we index this back into a grid

array([[ 0,  0],
       [ 1,  1],
       [ 2,  2],
       [ 3,  3],
       [ 4,  4],
       [ 5,  5],
       [ 6,  6],
       [ 7,  7],
       [ 8,  8],
       [ 9,  9],
       [10, 10],
       [10, 11],
       [11, 10],
       [11, 11],
       [12, 12],
       [12, 13],
       [13, 12],
       [13, 13],
       [14, 14],
       [14, 15],
       [14, 16],
       [15, 14],
       [15, 15],
       [15, 16],
       [16, 14],
       [16, 15],
       [16, 16],
       [17, 17],
       [17, 18],
       [18, 17],
       [18, 18],
       [19, 19],
       [19, 20],
       [20, 19],
       [20, 20],
       [21, 21],
       [21, 22],
       [22, 21],
       [22, 22],
       [23, 23],
       [23, 24],
       [24, 23],
       [24, 24],
       [25, 25],
       [25, 26],
       [26, 25],
       [26, 26],
       [27, 27],
       [27, 28],
       [27, 29],
       [28, 27],
       [28, 28],
       [28, 29],
       [29, 27],
       [29, 28],
       [29, 29],
       [30, 30],
       [30, 31],
       [31, 30

In [7]:
nsimplices = len(poly.simplices)
outarr = [[] for _ in range(nsimplices)]
for row, coplanar in zip(*is_coplanar.nonzero()):
    outarr[row].append(coplanar)
outarr

[[0],
 [1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9],
 [10, 11],
 [10, 11],
 [12, 13],
 [12, 13],
 [14, 15, 16],
 [14, 15, 16],
 [14, 15, 16],
 [17, 18],
 [17, 18],
 [19, 20],
 [19, 20],
 [21, 22],
 [21, 22],
 [23, 24],
 [23, 24],
 [25, 26],
 [25, 26],
 [27, 28, 29],
 [27, 28, 29],
 [27, 28, 29],
 [30, 31],
 [30, 31],
 [32, 33, 34],
 [32, 33, 34],
 [32, 33, 34],
 [35, 36],
 [35, 36],
 [37, 38, 39],
 [37, 38, 39],
 [37, 38, 39],
 [40, 41],
 [40, 41],
 [42, 43],
 [42, 43],
 [44, 45, 46],
 [44, 45, 46],
 [44, 45, 46],
 [47, 48],
 [47, 48],
 [49, 50, 51],
 [49, 50, 51],
 [49, 50, 51],
 [52, 53],
 [52, 53],
 [54, 55],
 [54, 55],
 [56, 57, 58],
 [56, 57, 58],
 [56, 57, 58],
 [59, 60],
 [59, 60],
 [61, 62, 63],
 [61, 62, 63],
 [61, 62, 63],
 [64, 65],
 [64, 65],
 [66, 67],
 [66, 67],
 [68, 69],
 [68, 69],
 [70, 71, 72, 73, 74, 75, 76, 77],
 [70, 71, 72, 73, 74, 75, 76, 77],
 [70, 71, 72, 73, 74, 75, 76, 77],
 [70, 71, 72, 73, 74, 75, 76, 77],
 [70, 71, 72, 73, 74, 75, 76, 77],
 [70, 71,

In [8]:
%%timeit -r 50 -n 10000
coplanar_indices = [[] for _ in range(nsimplices)]
for face, index in zip(*is_coplanar.nonzero()):
    coplanar_indices[face].append(index)
# outarr = list(set(map(tuple, outarr)))
coplanar_indices = list(set(map(tuple, coplanar_indices)))
coplanar_indices
# So now we have our coplanar simplex indices. Extract back the

57.1 µs ± 5.61 µs per loop (mean ± std. dev. of 50 runs, 10,000 loops each)


In [9]:
%%timeit -r 50 -n 10000
coplanar_indices = [[] for _ in range(nsimplices)]

# Iterate over coplanar indices to build face lists
for face, index in zip(*is_coplanar.nonzero()):
    coplanar_indices[face].append(index)

# Remove duplicate faces, then sort the face indices by their minimum value
coplanar_indices = sorted(set(map(tuple, coplanar_indices)), key=lambda x: x[0])

# So now we have our coplanar simplex indices. Extract back the faces

coplanar_indices

57.7 µs ± 1.58 µs per loop (mean ± std. dev. of 50 runs, 10,000 loops each)


In [10]:
sorted(
    [np.array(sorted(set(poly.simplices[[ind]].flat))) for ind in coplanar_indices],
    key=lambda x: x[0],
)

NameError: name 'coplanar_indices' is not defined

In [ ]:
%%timeit -r 100 -n 10000
[np.fromiter(set(poly.simplices[[ind]].flat), np.int32) for ind in coplanar_indices]

89.9 µs ± 6.84 µs per loop (mean ± std. dev. of 100 runs, 10,000 loops each)


In [ ]:
%%timeit -r 100 -n 10000
[np.array(sorted(set(poly.simplices[[ind]].flat))) for ind in coplanar_indices]

102 µs ± 12.6 µs per loop (mean ± std. dev. of 100 runs, 10,000 loops each)


In [ ]:
%%timeit -r 100 -n 10000
[np.unique(poly.simplices[[ind]].flat) for ind in coplanar_indices]
# Upside of this (other than clarity) is the numbers are "mostly" sorted
# I think this is only true because the input lists are sorted, but maybe this doesnt matter?
# In any case, sorting above is cheap so we should keep doing that
## 200us without .flat, and faster without - oof

220 µs ± 14.3 µs per loop (mean ± std. dev. of 100 runs, 10,000 loops each)


In [ ]:
%%timeit -r 100 -n 10000
[np.unique(poly.simplices[[ind]]) for ind in coplanar_indices]
# Upside of this (other than clarity) is the numbers are "mostly" sorted
# I think this is only true because the input lists are sorted, but maybe this doesnt matter?
# In any case, sorting above is cheap so we should keep doing that
## 200us without .flat

185 µs ± 14.4 µs per loop (mean ± std. dev. of 100 runs, 10,000 loops each)


In [ ]:
[np.unique(poly.simplices[[ind]]) for ind in coplanar_indices]

[array([38, 40, 48], dtype=int32),
 array([14, 22, 24], dtype=int32),
 array([15, 23, 25], dtype=int32),
 array([ 2,  7, 10], dtype=int32),
 array([0, 6, 8], dtype=int32),
 array([39, 41, 49], dtype=int32),
 array([33, 36, 45], dtype=int32),
 array([17, 20, 29], dtype=int32),
 array([32, 34, 43], dtype=int32),
 array([16, 18, 27], dtype=int32),
 array([15, 21, 25, 30], dtype=int32),
 array([36, 40, 45, 48], dtype=int32),
 array([ 1,  3, 15, 28, 30], dtype=int32),
 array([22, 23, 24, 25], dtype=int32),
 array([15, 19, 23, 28], dtype=int32),
 array([34, 38, 43, 48], dtype=int32),
 array([ 1,  3,  9, 11], dtype=int32),
 array([14, 18, 22, 27], dtype=int32),
 array([18, 19, 22, 23, 26], dtype=int32),
 array([ 2,  7, 17, 29], dtype=int32),
 array([ 0,  2, 14, 27, 29], dtype=int32),
 array([ 0,  2,  8, 10], dtype=int32),
 array([ 8, 10, 43, 45, 48], dtype=int32),
 array([35, 39, 44, 49], dtype=int32),
 array([38, 39, 40, 41], dtype=int32),
 array([36, 37, 40, 41, 47], dtype=int32),
 array([ 

In [ ]:
poly.simplices[coplanar_indices]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (42,) + inhomogeneous part.

In [ ]:
set(map(tuple, mbri.faces))

{(0, 27, 14, 29, 2),
 (1, 3, 30, 15, 28),
 (1, 28, 19, 26, 4, 12, 42, 35, 44, 9),
 (2, 7, 10),
 (3, 1, 9, 11),
 (3, 11, 46, 37, 47, 13, 5, 31, 21, 30),
 (8, 0, 2, 10),
 (8, 6, 0),
 (8, 10, 45, 48, 43),
 (9, 44, 49, 46, 11),
 (16, 4, 26, 18),
 (16, 18, 27),
 (16, 27, 0, 6),
 (17, 7, 2, 29),
 (17, 20, 31, 5),
 (17, 29, 20),
 (18, 22, 14, 27),
 (18, 26, 19, 23, 22),
 (19, 28, 15, 23),
 (20, 24, 25, 21, 31),
 (24, 14, 22),
 (24, 20, 29, 14),
 (24, 22, 23, 25),
 (25, 15, 30, 21),
 (25, 23, 15),
 (32, 6, 8, 43),
 (32, 12, 4, 16, 6),
 (32, 34, 42, 12),
 (32, 43, 34),
 (33, 7, 17, 5, 13),
 (33, 13, 47, 36),
 (33, 36, 45),
 (33, 45, 10, 7),
 (34, 38, 39, 35, 42),
 (36, 47, 37, 41, 40),
 (40, 41, 39, 38),
 (41, 37, 46, 49),
 (41, 49, 39),
 (48, 38, 34, 43),
 (48, 40, 38),
 (48, 45, 36, 40),
 (49, 44, 35, 39)}

In [ ]:
set(
    map(tuple, [np.unique(poly.simplices[[ind]].flat) for ind in coplanar_indices])
) == set(map(tuple, map(sorted, mbri.faces)))

True

In [12]:
# %%timeit -r 10 -n 100
# lets compile everything together now:
poly = mbri
tol = 1e-15
nsimplices = len(poly._simplices)
is_coplanar = np.all(
    np.abs(poly._simplex_equations[:, None] - poly._simplex_equations) < tol, axis=2
)
coplanar_indices = [[] for _ in range(nsimplices)]

# Iterate over coplanar indices to build face index lists
for face, index in zip(*is_coplanar.nonzero()):
    coplanar_indices[face].append(index)

# Remove duplicate faces, then sort the face indices by their minimum value
coplanar_indices = sorted(set(map(tuple, coplanar_indices)), key=lambda x: x[0])

# Set method is faster: but let's try this
# Extract vertex indices from simplex indices and remove duplicates
faces = [np.unique(poly.simplices[[ind]]) for ind in coplanar_indices]
faces

[array([38, 40, 48], dtype=int32),
 array([14, 22, 24], dtype=int32),
 array([15, 23, 25], dtype=int32),
 array([ 2,  7, 10], dtype=int32),
 array([0, 6, 8], dtype=int32),
 array([39, 41, 49], dtype=int32),
 array([33, 36, 45], dtype=int32),
 array([17, 20, 29], dtype=int32),
 array([32, 34, 43], dtype=int32),
 array([16, 18, 27], dtype=int32),
 array([15, 21, 25, 30], dtype=int32),
 array([36, 40, 45, 48], dtype=int32),
 array([ 1,  3, 15, 28, 30], dtype=int32),
 array([22, 23, 24, 25], dtype=int32),
 array([15, 19, 23, 28], dtype=int32),
 array([34, 38, 43, 48], dtype=int32),
 array([ 1,  3,  9, 11], dtype=int32),
 array([14, 18, 22, 27], dtype=int32),
 array([18, 19, 22, 23, 26], dtype=int32),
 array([ 2,  7, 17, 29], dtype=int32),
 array([ 0,  2, 14, 27, 29], dtype=int32),
 array([ 0,  2,  8, 10], dtype=int32),
 array([ 8, 10, 43, 45, 48], dtype=int32),
 array([35, 39, 44, 49], dtype=int32),
 array([38, 39, 40, 41], dtype=int32),
 array([36, 37, 40, 41, 47], dtype=int32),
 array([ 

In [24]:
%%timeit -r 10 -n 10000
poly._simplex_equations[[equation_index[0] for equation_index in coplanar_indices]]

3.04 µs ± 145 ns per loop (mean ± std. dev. of 10 runs, 10,000 loops each)


In [ ]:
%%timeit -r 10 -n 10000
# lets compile everything together now:
is_coplanar = np.all(
    np.abs(poly._simplex_equations[:, None] - poly._simplex_equations) < tol, axis=2
)
coplanar_indices = [[] for _ in range(nsimplices)]

300 µs ± 7.5 µs per loop (mean ± std. dev. of 10 runs, 10,000 loops each)


In [ ]:
%%timeit -r 10 -n 10000
# Iterate over coplanar indices to build face index lists
for face, index in zip(*is_coplanar.nonzero()):
    coplanar_indices[face].append(index)

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
%%timeit -r 10 -n 10000
# Remove duplicate faces, then sort the face indices by their minimum value
coplanar_indices = sorted(set(map(tuple, coplanar_indices)), key=lambda x: x[0])

In [ ]:
%%timeit -r 10 -n 10000
# Set method is faster: but let's try this
# Extract vertex indices from simplex indices and remove duplicates
faces = [np.unique(poly.simplices[[ind]]) for ind in coplanar_indices]
faces

In [ ]:
tol = 1e-15
is_coplanar = np.all(
    np.abs(self._simplex_equations[:, None] - self._simplex_equations) < tol,
    axis=2,
)
coplanar_indices = [[] for _ in range(len(self._simplices))]

# Iterate over coplanar indices to build face index lists
for face, index in zip(*is_coplanar.nonzero()):
    coplanar_indices[face].append(index)

# Remove duplicate faces, then sort the face indices by their minimum value
coplanar_indices = sorted(set(map(tuple, coplanar_indices)), key=lambda x: x[0])

# Set method is faster: but let's try this
# Extract vertex indices from simplex indices and remove duplicates
faces = [np.unique(self.simplices[[ind]]) for ind in coplanar_indices]
self._faces = faces
# self._equations = np.array(list(equation_groups.keys()))

NameError: name 'self' is not defined

In [21]:
coplanar_indices
%timeit -r 20 -n 100000 [np.array(coplanar) for coplanar in coplanar_indices]
%timeit -r 20 -n 100000 list(map(np.array,coplanar_indices))

13.4 µs ± 929 ns per loop (mean ± std. dev. of 20 runs, 100,000 loops each)
11.6 µs ± 140 ns per loop (mean ± std. dev. of 20 runs, 100,000 loops each)


In [20]:
list(map(np.array, coplanar_indices))

[array([0]),
 array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9]),
 array([10, 11]),
 array([12, 13]),
 array([14, 15, 16]),
 array([17, 18]),
 array([19, 20]),
 array([21, 22]),
 array([23, 24]),
 array([25, 26]),
 array([27, 28, 29]),
 array([30, 31]),
 array([32, 33, 34]),
 array([35, 36]),
 array([37, 38, 39]),
 array([40, 41]),
 array([42, 43]),
 array([44, 45, 46]),
 array([47, 48]),
 array([49, 50, 51]),
 array([52, 53]),
 array([54, 55]),
 array([56, 57, 58]),
 array([59, 60]),
 array([61, 62, 63]),
 array([64, 65]),
 array([66, 67]),
 array([68, 69]),
 array([70, 71, 72, 73, 74, 75, 76, 77]),
 array([78, 79, 80]),
 array([81, 82]),
 array([83, 84, 85, 86, 87, 88, 89, 90]),
 array([91, 92, 93]),
 array([94, 95])]

In [15]:
poly._coplanar_simplices

[array([0], dtype=int32),
 array([1], dtype=int32),
 array([2], dtype=int32),
 array([3], dtype=int32),
 array([4], dtype=int32),
 array([5], dtype=int32),
 array([6], dtype=int32),
 array([7], dtype=int32),
 array([8], dtype=int32),
 array([9], dtype=int32),
 array([10, 11], dtype=int32),
 array([12], dtype=int32),
 array([13], dtype=int32),
 array([14], dtype=int32),
 array([16, 15], dtype=int32),
 array([17, 18], dtype=int32),
 array([19], dtype=int32),
 array([20], dtype=int32),
 array([21], dtype=int32),
 array([22], dtype=int32),
 array([24, 23], dtype=int32),
 array([25], dtype=int32),
 array([26], dtype=int32),
 array([27, 28, 29], dtype=int32),
 array([30, 31], dtype=int32),
 array([32, 33, 34], dtype=int32),
 array([35, 36], dtype=int32),
 array([37], dtype=int32),
 array([38, 39], dtype=int32),
 array([40], dtype=int32),
 array([41], dtype=int32),
 array([42, 43], dtype=int32),
 array([44, 45, 46], dtype=int32),
 array([47], dtype=int32),
 array([48], dtype=int32),
 array([4

In [24]:
poly._coplanar_simplices[0:10]

[array([0], dtype=int32),
 array([1], dtype=int32),
 array([2], dtype=int32),
 array([3], dtype=int32),
 array([4], dtype=int32),
 array([5], dtype=int32),
 array([6], dtype=int32),
 array([7], dtype=int32),
 array([8], dtype=int32),
 array([9], dtype=int32)]

In [34]:
verts = johnfam.get_shape("Metabidiminished Rhombicosidodecahedron").vertices
verts = cube.vertices

In [7]:
%%timeit -r 10 -n 100
ConvexPolyhedron(mbri.vertices)

5.08 ms ± 543 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [8]:
%%timeit -r 10 -n 1000
ConvexPolyhedron(cube.vertices)

659 µs ± 8.77 µs per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


In [12]:
poly = mbri
tol = 1e-15
is_coplanar = np.all(
    np.abs(poly._simplex_equations[:, None] - poly._simplex_equations) < tol,
    axis=2,
)
coplanar_indices = [[] for _ in range(len(poly._simplices))]

# Iterate over coplanar indices to build face index lists
for face, index in zip(*is_coplanar.nonzero()):
    coplanar_indices[face].append(index)

# Remove duplicate faces, then sort the face indices by their minimum value
coplanar_indices = sorted(set(map(tuple, coplanar_indices)), key=lambda x: x[0])

# Extract vertex indices from simplex indices and remove duplicates
faces = [np.unique(poly.simplices[[ind]]) for ind in coplanar_indices]

# Copy the simplex equation for one of the simplices on each face
poly._simplex_equations[[equation_index[0] for equation_index in coplanar_indices]]
# Convert the simplex indices to numpy arrays and save
list(map(np.array, coplanar_indices))

[array([0]),
 array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9]),
 array([10, 11]),
 array([12, 13]),
 array([14, 15, 16]),
 array([17, 18]),
 array([19, 20]),
 array([21, 22]),
 array([23, 24]),
 array([25, 26]),
 array([27, 28, 29]),
 array([30, 31]),
 array([32, 33, 34]),
 array([35, 36]),
 array([37, 38, 39]),
 array([40, 41]),
 array([42, 43]),
 array([44, 45, 46]),
 array([47, 48]),
 array([49, 50, 51]),
 array([52, 53]),
 array([54, 55]),
 array([56, 57, 58]),
 array([59, 60]),
 array([61, 62, 63]),
 array([64, 65]),
 array([66, 67]),
 array([68, 69]),
 array([70, 71, 72, 73, 74, 75, 76, 77]),
 array([78, 79, 80]),
 array([81, 82]),
 array([83, 84, 85, 86, 87, 88, 89, 90]),
 array([91, 92, 93]),
 array([94, 95])]

In [28]:
%%timeit -r 10 -n 10000
[np.unique(poly.simplices[[ind]]) for ind in coplanar_indices]

177 µs ± 5.02 µs per loop (mean ± std. dev. of 10 runs, 10,000 loops each)


In [8]:
%%timeit -r 10 -n 100
# [np.fromiter(set(poly.simplices[[ind]].flat), np.int32) for ind in coplanar_indices]
mbri._sort_simplices()

1.07 ms ± 114 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [4]:
%%timeit -r 10 -n 1000
# [np.fromiter(set(poly.simplices[[ind]].flat), np.int32) for ind in coplanar_indices]
mbri._sort_simplices()

1.33 ms ± 242 µs per loop (mean ± std. dev. of 10 runs, 1,000 loops each)
